### ISSUE TITLE
Split a large XML file into multiple documents

### ISSUE THREAD

**Issue by sastafford** [sastafford/marklogic-spring-batch#100]
As a developer
I want to TITLE
So that I can load that data into MarkLogic

Given a large XML file on the filesystem
When I run the SplitXmlFileIntoManyDocuments job
Then x>1 documents are loaded into MarkLogic

We want this job to mimic the functionality and parameters of the [split xml files task from mlcp](http://docs.marklogic.com/guide/mlcp/import#id_65814).  

Would recommend that you look into the [StaxEventItemReader](http://docs.spring.io/spring-batch/trunk/reference/html/readersAndWriters.html#StaxEventItemReader) from Spring Batch for your reader.  The Processor will probably be a pass thru and then you can use the [DocumentItemWriter](https://github.com/sastafford/marklogic-spring-batch/blob/master/core/src/main/java/com/marklogic/spring/batch/item/DocumentItemWriter.java) for the write.

**Comment by rjrudin** [comment]
@sastafford I don't think we need a separate jo/config for this. I think these are just more config options on an XmlFileReader class in "core". I think we'd want mlcp-like config options - i.e. the aggregate ones - on that Reader with setters so that a Config class could set them based on job parameters. 

We can then have an "ImportXmlFilesConfig" config class in jobs that provides one way of using that Reader, and a developer could always make their own Config class as well that uses the Reader.

**Comment by sastafford** [comment]
@mplotnic - Rob is referring to building the functionality in this task in the JobConfig that already exists called LoadXmlDocumentsFromDirectoryConfig.  I agree that eventually that will probably need to be done.  

But the priority is for you to learn to put together a simple JobConfig and get familiar with Spring Batch.  I would like you to write a new JobConfig and use LoadXmlDocumentsFromDirectoryConfig as inspiration.  Once you get over your learning curve and you get this functionality working, let's circle back and discuss what @rjrudin is talking about.

**Comment by sastafford** [comment]
https://github.com/sastafford/marklogic-spring-batch/blob/master/infrastructure/src/main/java/com/marklogic/spring/batch/item/reader/SplitXmlDocumentReader.java

This reader will do the work, string it with a MarkLogicItemWriter
