### ISSUE TITLE
Change data capture from upstream relational database

### ISSUE THREAD

**Issue by jmakeig** [sastafford/marklogic-spring-batch#137]
As a developer I want to be able to get only that changes from an upstream relational database since the last time I asked to avoid putting unnecessary load on the source database or the target MarkLogic instance. 

I'd like to be able to subscribe to a “change feed” from the database such that, changes are pushed to my long-running Java listener and written to MarkLogic. 

Alternatively, I’d like to be able to query the database to select only the rows I need, and no more, based on some information about the last diff batch that I extracted (e.g. last updated date or rowid) This subset must be referentially consistent.

**Comment by sastafford** [comment]
Querying RDBMS deltas is going to require some assumptions on the upstream database but I think that's ok.  

I also think we have several issues embedded in this one issue.  The change feed scenario is one issue and may involve the use of another framework called Spring Integration (similar to Camel).  Just speculating on that implementation detail.  We will call this the "push issue" part.  

The other issue is the "pull issue" part.  Query a database for the delta instead of the information being pushed.

**Comment by rjrudin** [comment]
@jmakeig I think the latter approach is more feasible and also better for the worst-case scenario, which is that the source database has no way of supporting the former. And for the former, I think every change feed is going to be database-specific, making it difficult to write any general code. 

Thoughts on doing the latter:

- As part of a migration, a hash or something similar of each entity has to be written out to some sort of storage - e.g. a file on disk, or perhaps in the corresponding ML document for the entity (that's normally too slow for reading back) - I've found a Java properties file to work well here, though that can impose memory constraints.
- When the migration is next run, each entity constructed from a row in a ResultSet is hashed and compared to the hash from the previous migration. If the hashes are equal, the entity is discarded - so doing this in a Processor is often good

**Comment by sastafford** [comment]
Closing issue as out of scope for MSB project.  I believe that this would be a good issue for the [ml-migration-starter](https://github.com/rjrudin/ml-migration-starter) project.
