### ISSUE TITLE
Gradle Eclipse configuration is incomplete

### ISSUE THREAD

**Issue by jmakeig** [sastafford/marklogic-spring-batch#144]
```bash
git fetch sastafford
git checkout -b dev sastafford/dev
gradle clean build eclipse -x test
```

I’m able to import the project successfully into Eclipse (Mars, OS X). However, Eclipse complains that all of the source folders are missing:

* `src/main/java`
* `src/test/java`
* `src/test/resources`

Manually adding them in Eclipse fixes the problem, but I would have expected that to be out-of-the-box with the `eclipse` task, as it seems to work in other projects.

**Comment by jmakeig** [comment]
If I build from the core directory and import that into Eclipse things seem to work. That’s not obvious, though. I’ll add a README to core if someone can confirm that this is the correct procedure.

**Comment by sastafford** [comment]
I'm running Eclipse IDE for Java Developers Version: Mars.1 Release (4.5.1).  I cloned the repository into a temp repository and ran the following command 

    gradle clean build eclipse -x test

From Eclipse, I then executed the following commands

1. File -> Import
2. Import Source = Gradle Project
3. Root Directory = PROJECT_DIR/marklogic-spring-batch
4. Gradle Wrapper

It seemed that after running these steps, that everything imported fine, including the recognition of the above folders for each gradle sub-project.  I have been coding with IntelliJ since it seems to be more Gradle friendly and because Eclipse had a lack of support of Gradle within the tool.  It seems that Eclipse Mars addresses some of those shortcomings.  

@jmakeig can you confirm running the above steps and see if you have success?  

I think the correct fix is to change the CONTRIBUTING.md file on the project root directory.

**Comment by jmakeig** [comment]
Ah, I wasn't importing as a Gradle project. I thought the `eclipse` task obviated that.

**Comment by rjrudin** [comment]
"gradle eclipse" generates a .classpath and a .project file. You can then "Import existing project" in Eclipse, and you should be good to go.

The free IntelliJ is a bit better - it has a Gradle plugin, and you just click the synchronize button, and it does everything needed.

**Comment by jmakeig** [comment]
> "gradle eclipse" generates a .classpath and a .project file. You can then "Import existing project" in Eclipse, and you should be good to go.

With Eclipse, you'll still need the Gradle plugin to import the top-level directory. Eclipse doesn't support multi-project Gradle definitions out-of-the-box. Thus, you need to run `gradle eclipse` in each of the sub-projects and import them separately as their own individual projects or use the Eclipse Gradle plugin (and not the `eclipse` task); it’s either/or, but not both.
