### ISSUE TITLE
Exporting Documents as Files

### ISSUE THREAD

**Issue by rjrudin** [sastafford/marklogic-spring-batch#15]
Use case is - customer wants to specify a search query, and any document that matches it should be written to a directory or to a zip file. And while this is happening, the customer wants status on the job - which Spring Batch should be able to provide very easily.

**Comment by sastafford** [comment]
As a developer 
I want to TITLE
So that there is an example of a job exporting data from MarkLogic

Given some predefined query, Q
When Q is executed against a MarkLogic database
 * query_filter = Q
 * output_file_path = some directory
Then the result set of Q will be written to the file system in output_file_path

It should mimic the same [export parameters as mlcp.](http://docs.marklogic.com/guide/mlcp/export)

**Comment by rjrudin** [comment]
Plan is to assign this to Shan

**Comment by venuiyengar** [comment]
@sastafford I have written a simple URI test job that does the following:
1. Unit test populates the data to ML as part of setup
2. The job calls MarkLogicItemReader and passes the existing module to query the URIS
3. The FlatFileItemWriter writes a file with the found URIs to file system

Issue - When I write the file for some reason the writer gets called twice, once it creates an empty file and second time it creates the file with the URIs that are returned. So far I can not figure out why it gets called twice. Any idea?

**Comment by venuiyengar** [comment]
@sastafford 
Never mind adding JobScope fixed the issue and now it does not get called twice.

**Comment by sastafford** [comment]
See ExportContentFromMarkLogicJobTest in samples
