### ISSUE TITLE
Persist the JobRepository in MarkLogic

### ISSUE THREAD

**Issue by sastafford** [sastafford/marklogic-spring-batch#2]

**Comment by rjrudin** [comment]
It's been a while since I looked at the docs for doing the same thing, but IIRC, I think we could use something like XStream/XMLBeans/JAXB/etc to serialize Spring Batch Java objects to XML (or use Jackson to serialize to JSON... JSON may be a better fit here, and I like Jackson a lot) and then stuff them into MarkLogic.

I think we'd want URI-ish directories and collections to guarantee there's no overlap with application data - e.g. 

Directory: /marklogic.com/spring-batch/job/123.json
Collection: http://marklogic.com/spring-batch/job

**Comment by sastafford** [comment]
I've been using JAXB but I'm open.  I do think using some type of POJO is the direction we want to take.  I think the next step would be to do a quick review of document format.  I think that job-instance would be the root element and job-execution objects would be child elements.  That fits the type of queries that would be hit from an admin interface (to be developed)

    <job-instance>
        <metadata>
        <job-execution />
        <job-execution />
    </job-instance>

**Comment by sastafford** [comment]
This is a first cut at the JobRepository code.  Most of the work was setting up the POJO classes to set persist job executions.  Will open more detailed tickets from this point forward.
