### ISSUE TITLE
Should we use the following package naming construct?

### ISSUE THREAD

**Issue by sastafford** [sastafford/marklogic-spring-batch#29]
I was reviewing how Spring Batch names their packages.  All ItemReader and ItemWriters are located under the following package

**org.springframework.batch.item**

ItemReader and ItemWriters are going to be the reusable piece parts that people will use to construct Steps and Jobs.  I propose that we rearrange our current ItemReaders and ItemWriters into the following package.  

**org.springframework.batch.item.marklogic**

I also recommend that we rename the following classes and put into this package. 
* CorbReader -> UriItemReader
* CorbWriter -> ProcessUriWriter
* DeleteUriWriter -> DeleteUriItemWriter
* CollectionUrisReader -> CollectionUriItemReader
* DocumentItemWriter
* DocumentItemReader

**Comment by rjrudin** [comment]
I think we still want a root package of "com.marklogic", since this is really MarkLogic code, not Spring code (the Spring folks may take issue to us using a root package of org.springframework). 

As for whether it's "spring" or "springframework" next, I've always found the latter to be a bit verbose - Spring is widely known in Java land. So I favor "com.marklogic.spring.batch" as the root package. And that would mean "com.marklogic.spring.batch.item" for item reader/writer/processor stuff.

**Comment by sastafford** [comment]
OK, I'm good with you.
