### ISSUE TITLE
Ingest shapefiles into MarkLogic

### ISSUE THREAD

**Issue by sastafford** [sastafford/marklogic-spring-batch#42]
As a developer
I want to TITLE
So that I can run geoqueries on ESRI shapefiles

1. ItemReader - read shapefiles from a directory
2. ItemProcessor - bounce them against either the Ogre web service or the Ogre command line
3. ItemWriter - write them to MarkLogic as GeoJSON files (either JSON or XML).

JobExecution Idea
That could be packaged up as a single executable JAR via Spring Boot, and versioned too.
Now someone could download a single JAR and run it to quickly ingest shapefiles into ML:
`java -jar marklogic-shapefile-ingestor.jar ~/my-shapefiles`

**Comment by rjrudin** [comment]
I think we can have the generic components in this project, and then a separate Github repo... or possibly a separate build in this one, I'm not sure - that stitches things together into an executable. Actually, a separate project is probably the way to go so that we can use Spring Boot and a Main class and then produce a clean executable jar for this one purpose.

**Comment by rjrudin** [comment]
I think this would be a great project under ./examples/shapefile-project
