### ISSUE TITLE
Pass only the job name without the package name and suffix '.class' to the Jobs Utility

### ISSUE THREAD

**Issue by sastafford** [sastafford/marklogic-spring-batch#91]
As a developer
I want to TITLE
So that I can minimize the complexity of the --config parameter for the jobs utility

**Comment by rjrudin** [comment]
I looked into this initially - here's the Spring class that does the work - http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/context/annotation/ClassPathScanningCandidateComponentProvider.html .

The problem is that the less of the package that is specified, the longer it takes for the specified class to be found. IIRC, searching on "/" took about 12 seconds, and of course that will only get worse as more libraries are added to the classpath.

Including at least "com", or the root package, does make a significant difference. I think that may have led to 2 to 3 seconds for finding the class. 

So one option would be to support e.g. "com.MyConfig", where everything before the last period will be used for scanning the classpath for Configuration classes, and then the one with a class name matching what's after the last period will be selected. That is certainly an improvement over having to type e.g "com.marklogic.spring.batch.something.else.MyConfig". But it's also not that intuitive.

**Comment by sastafford** [comment]
What if we dictated that all jobs were to exist in a particular package?  Is that asking too much?

**Comment by rjrudin** [comment]
I think so, and it increases the chance of duplicate class names. 

I don't know if this will help, but we could require *.config.MyConfig - i.e. the config class must be in a package named config. I'm not sure if that will speed up how quickly Spring can find configuration classes though - I think it matters a lot more if the first or second levels of the package are defined.

**Comment by sastafford** [comment]
Adding the package name is not that big of a nuisance and I would be ok dropping this issue.  

Batch processing are not sub-second operations.  For a long running batch process, >10 seconds is not much in the bigger picture.  It matters when you are unit testing or running small tests.
